#include "bls_ibe_util.h"
#include <pbc/pbc.h>
#include <stdio.h>

#define PARAM_FILE "a.param"
#define MSK_FILE "master_secret_key.dat"
#define MAX_FILENAME_LEN 512

int main(int argc, char **argv) {
    // Usage: server_keygen <identity> <blinding_factor_file>
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <identity> <blinding_factor_file>\n", argv[0]);
        fprintf(stderr, "       (Blinding factor file is generated by user_keygen_init)\n");
        return 1;
    }
    const char *ID = argv[1];
    const char *blinding_factor_file = argv[2];

    pairing_t pairing;
    element_t Q_id, msk, usk_inv, msk_blinded, d_partial;

    // Initialize pairing
    initialize_pairing(pairing, PARAM_FILE);

    // Load master secret key
    load_master_secret(pairing, msk, MSK_FILE);

    // Load user's blinding factor (usk_inv)
    load_zr_element(pairing, usk_inv, blinding_factor_file);

    // Compute Q = H(ID)
    hash_id_to_G1(Q_id, ID, pairing);

    // Compute blinded exponent: msk_blinded = msk * usk_inv
    element_init_Zr(msk_blinded, pairing);
    element_mul(msk_blinded, msk, usk_inv);

    // Compute partial key: d_partial = Q_id ^ msk_blinded
    element_init_G1(d_partial, pairing);
    element_pow_zn(d_partial, Q_id, msk_blinded);

    // Save partial key to file (to be sent back to user)
    char partial_key_file[MAX_FILENAME_LEN];
    snprintf(partial_key_file, sizeof(partial_key_file), "%s_partial_key.dat", ID);
    save_partial_key(d_partial, partial_key_file); // Reuse existing save function for G1

    printf("Partial key for identity '%s' generated using blinding factor from '%s'.\n", ID, blinding_factor_file);
    printf("  Partial key saved to: %s (Send this back to the user)\n", partial_key_file);

    // Cleanup
    element_clear(Q_id);
    element_clear(msk);
    element_clear(usk_inv);
    element_clear(msk_blinded);
    element_clear(d_partial);
    pairing_clear(pairing);

    return 0;
}