#include "bls_ibe_util.h"
#include <pbc/pbc.h>
#include <stdio.h>

#define PARAM_FILE "a.param"
#define MAX_FILENAME_LEN 512

int main(int argc, char **argv) {
    // Usage: user_keygen_finalize <identity> <partial_key_file>
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <identity> <partial_key_file>\n", argv[0]);
        fprintf(stderr, "       (Partial key file is generated by server_keygen)\n");
        return 1;
    }
    const char *ID = argv[1];
    const char *partial_key_file = argv[2];

    pairing_t pairing;
    element_t usk, d_partial, d_final;

    // Determine user secret filename
    char user_secret_file[MAX_FILENAME_LEN];
    snprintf(user_secret_file, sizeof(user_secret_file), "%s_user_secret.dat", ID);

    // Determine final private key filename
    char final_key_file[MAX_FILENAME_LEN];
    snprintf(final_key_file, sizeof(final_key_file), "%s_private_key.dat", ID);

    // Initialize pairing
    initialize_pairing(pairing, PARAM_FILE);

    // Load user's *own* secret usk
    load_zr_element(pairing, usk, user_secret_file);

    // Load partial key (d_partial) from server
    load_partial_key(pairing, d_partial, partial_key_file); // Reuse existing load function for G1

    // Compute final key: d_final = d_partial ^ usk
    element_init_G1(d_final, pairing);
    element_pow_zn(d_final, d_partial, usk);

    // Save the final private key (this is the key used by sign/decrypt)
    save_user_private_key(d_final, final_key_file); // Use standard save function

    printf("Final private key for user '%s' generated from partial key '%s'.\n", ID, partial_key_file);
    printf("  Final key saved to: %s\n", final_key_file);

    // Optional: Securely delete intermediate files (consider adding proper secure delete utility)
    printf("  Consider securely deleting: %s and %s\n", user_secret_file, partial_key_file);
    // remove(user_secret_file); // Standard remove is not secure
    // remove(partial_key_file);

    // Cleanup
    element_clear(usk);
    element_clear(d_partial);
    element_clear(d_final);
    pairing_clear(pairing);

    return 0;
}